import type { Assignment, BehaviorRating, LeaderboardEntry, Participant, Task } from '../../domain/models'
import { benefitLabels, scheduleLabels, windowLabels } from '../shared/labels'
import { Leaderboard } from '../shared/Leaderboard'
import { formatDate, statusLabel, taskRewardLabel } from '../shared/formatters'

type Props = { participant:Participant|null; participants:Participant[]; tasks:Task[]; filteredTasks:Task[]; reviewTasks:Task[]; assignments:Assignment[]; ratings:BehaviorRating[]; day:LeaderboardEntry[]; week:LeaderboardEntry[]; month:LeaderboardEntry[]; date:string; loading:boolean; busyTask:number|null; busyBehavior:number|null; controls:React.ReactNode; onComplete:(task:Task)=>void; onConfirm:(task:Task,rating:number)=>void; onRate:(person:Participant,rating:number)=>void }
export function Planner(props:Props) {
  if (!props.participant) return <section className="view-dashboard"><Leaderboard title="Рейтинг дня" entries={props.day}/><Leaderboard title="Рейтинг недели" entries={props.week}/><Leaderboard title="Рейтинг месяца" entries={props.month}/></section>
  const current = props.participant
  return <section className="workspace"><div className="task-panel"><div className="section-heading"><div><p className="eyebrow">{formatDate(props.date)}</p><h2>Задачи дня</h2></div></div><div className="task-list">
    {props.loading && <p className="empty">Загружаю семейный план...</p>}{!props.loading && props.filteredTasks.length===0 && <p className="empty">Назначьте обязанности, и здесь появится план дня.</p>}
    {props.filteredTasks.map(task=><article className="task-row" key={task.id}><div className="task-main"><div className="task-title-line"><span className={`status ${task.status}`}>{statusLabel(task.status)}</span><span className="task-owner">{task.personName}</span></div><h3>{task.choreTitle}</h3>{task.choreDescription.trim()&&<div className="task-description"><p>{task.choreDescription}</p></div>}<p>{task.schedule==='daily'?windowLabels[task.timeWindow]:scheduleLabels[task.schedule]} · {taskRewardLabel(props.assignments,task)}</p><div className="tag-row"><span>{benefitLabels[task.benefitType]}</span></div></div><div className="task-actions">
      {task.status==='pending'&&<button disabled={props.busyTask===task.id||current.id!==task.participantId} onClick={()=>props.onComplete(task)}>{current.id===task.participantId?'Сделано':`Ждет ${task.personName}`}</button>}
      {task.status==='completed'&&<>{current.id!==task.participantId?<div className="rating-buttons" aria-label="Оценка выполнения">{[1,2,3,4,5].map(r=><button disabled={props.busyTask===task.id} key={r} onClick={()=>props.onConfirm(task,r)}>{r}</button>)}</div>:<span className="action-hint">Ждет подтверждения</span>}</>}{task.status==='confirmed'&&<strong>{task.reward.toFixed(0)} ⭐</strong>}
    </div></article>)}</div></div><aside className="side-stack"><div className="side-controls">{props.controls}</div><div className="side-column"><Leaderboard title="Рейтинг дня" entries={props.day}/><section className="panel"><h2>На подтверждение</h2><div className="review-list">{props.reviewTasks.length===0&&<p className="settings-note">Пока нет чужих дел, которые ждут оценки.</p>}{props.reviewTasks.map(task=><article className="review-card" key={task.id}><div><strong>{task.choreTitle}</strong><span>{task.personName}</span></div><div className="rating-buttons">{[1,2,3,4,5].map(r=><button disabled={props.busyTask===task.id} key={r} onClick={()=>props.onConfirm(task,r)}>{r}</button>)}</div></article>)}</div></section>
    <section className="panel"><h2>Поведение дня</h2><div className="behavior-list">{props.participants.filter(p=>p.id!==current.id).map(person=>{const selected=props.ratings.find(r=>r.raterParticipantId===current.id&&r.targetParticipantId===person.id)?.rating;return <div className="behavior-row" key={person.id}><span>{person.name}</span><div className="rating-buttons">{[1,2,3,4,5].map(r=><button aria-pressed={selected===r} className={selected===r?'selected':''} disabled={props.busyBehavior===person.id} key={r} onClick={()=>props.onRate(person,r)}>{r} 🙂</button>)}</div></div>})}</div></section></div></aside></section>
}
