import { useState } from 'react'
import { useFamilyLife } from '../../application/useFamilyLife'
import { emptyDraft, entryDraft, type FamilyDraft, type FamilyEntry, type SportSession } from '../../domain/family'
import type { Participant } from '../../domain/models'
import { localDate } from '../../domain/date'
import { sportProgress } from '../../domain/sport'
import '../family/family.css'
import './sports.css'

export function Sports({ current, participants, date }: { current: Participant; participants: Participant[]; date: string }) {
  const data = useFamilyLife()
  const [person, setPerson] = useState(current.id)
  const [activity, setActivity] = useState('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')
  const [archive, setArchive] = useState(false)
  const [editor, setEditor] = useState<{ entry?: FamilyEntry; draft: FamilyDraft } | null>(null)
  const family = participants.filter(p => p.role === 'parent' || p.role === 'child')
  const sessions = data.entries.filter(e => e.kind === 'sport' && e.sport)
  const selected = sessions.filter(e => e.archived === archive && (!person || e.participantIds.includes(person)) && (!activity || e.sport?.activity === activity) && (!from || e.date >= from) && (!to || e.date <= to)).sort((a, b) => b.date.localeCompare(a.date) || b.id - a.id)
  const progress = sportProgress(selected)
  function start() { setEditor({ draft: { ...emptyDraft(date > localDate() ? localDate() : date), participantIds: [current.role === 'parent' && family.some(p => p.id === person && p.active) ? person : current.id], sport: { activity: 'Общая тренировка', minutes: 30, distanceKm: 0, exercises: [] } } }) }
  return <section className="family-life" aria-label="Семейный спорт">
    <header className="family-hero"><div><p className="eyebrow">FamilyQuest · движение вместе</p><h1>Спорт в своём темпе</h1><p>Занятия всей семьи и личный прогресс. Каждая тренировка — шаг вперёд.</p><button className="family-primary" onClick={start} disabled={data.busy}>+ Записать занятие</button></div><div className="family-hero-garden"><span aria-hidden="true">🏃 🚴 🏊</span><strong>Сравниваем себя с собой</strong><p>История сохраняется после перерывов.</p></div></header>
    {data.error && <div role="alert" className="notice">{data.error}<button disabled={data.busy} onClick={() => { void data.refresh().catch(() => {}) }}>Обновить данные</button></div>}
    {editor && <SportEditor key={`${editor.entry?.id ?? 'new'}-${editor.entry?.version ?? 0}`} initial={editor.draft} current={current} participants={family} busy={data.busy} stale={!!editor.entry && sessions.some(e => e.id === editor.entry?.id && e.version !== editor.entry.version)} onReload={() => { const latest = sessions.find(e => e.id === editor.entry?.id); if (latest) setEditor({ entry: latest, draft: entryDraft(latest) }) }} onClose={() => setEditor(null)} onSave={async draft => { if (await data.save('sport', draft, editor.entry)) setEditor(null) }} />}
    <section className="family-section">
      <div className="sport-filters"><label>Участник<select value={person} onChange={e => setPerson(Number(e.target.value))}><option value={0}>Вся семья</option>{family.map(p => <option key={p.id} value={p.id}>{p.name}{!p.active ? ' (архив)' : ''}</option>)}</select></label><label>Вид спорта<select value={activity} onChange={e => setActivity(e.target.value)}><option value="">Все занятия</option>{[...new Set(sessions.map(e => e.sport!.activity))].sort().map(a => <option key={a}>{a}</option>)}</select></label><label>С даты<input type="date" value={from} onInput={e => setFrom(e.currentTarget.value)} /></label><label>По дату<input type="date" value={to} onInput={e => setTo(e.currentTarget.value)} /></label><label className="family-checkbox"><input type="checkbox" checked={archive} onChange={e => setArchive(e.target.checked)} />Архив</label></div>
      {from && to && from > to && <p role="alert">Начало периода должно быть не позднее окончания.</p>}
      {data.loading ? <p role="status">Загружаем занятия…</p> : <>
        <div className="family-stats"><div><strong>{selected.length}</strong><span>занятий за выбранный период</span></div><div><strong>{progress.minutes.toLocaleString('ru-RU')}</strong><span>минут движения</span></div><div><strong>{progress.distance.toLocaleString('ru-RU')}</strong><span>километров</span></div></div>
        {selected.length > 0 && <><h2>Регулярность по неделям</h2><div className="sport-weeks">{progress.weeks.map(w => <div key={w.date}><span>{w.date}</span><meter aria-label={`Неделя с ${w.date}: ${w.minutes} минут`} min={0} max={Math.max(...progress.weeks.map(x => x.minutes), 1)} value={w.minutes} /><strong>{w.minutes.toLocaleString('ru-RU')} мин · {w.count} зан.</strong></div>)}</div></>}
        {person !== 0 && progress.exercises.length > 0 && <><h2>Личный прогресс в упражнениях</h2><p className="family-muted">Первый и последний результат за выбранный период. Вес указан для одного подхода; сравнивайте также повторения.</p><div className="family-grid">{progress.exercises.map(x => <article className="family-card" key={x.name}><h3>{x.name}</h3><p>{x.first.date}: {x.first.sets} × {x.first.reps} · {x.first.weightKg} кг</p><p>{x.last.date}: {x.last.sets} × {x.last.reps} · {x.last.weightKg} кг</p><strong>Максимальный записанный вес: {x.best} кг</strong></article>)}</div></>}
        <h2>История занятий</h2>{!selected.length && <div className="family-empty"><span aria-hidden="true">🏃</span><h3>Здесь появятся ваши занятия</h3><p>Запишите прогулку, плавание, тренировку или занятие в секции. Проверьте фильтры, если запись уже была.</p></div>}
        <div className="family-grid">{selected.map(e => <article className="family-card" key={e.id}><p className="family-muted">{e.date} · {family.find(p => p.id === e.participantIds[0])?.name ?? 'Участник'}</p><h3>{e.title}</h3><p>{e.sport!.activity} · {e.sport!.minutes} мин{e.sport!.distanceKm > 0 ? ` · ${e.sport!.distanceKm} км` : ''}</p>{(e.sport!.exercises ?? []).map((x, i) => <p key={i}>{x.name}: {x.sets} × {x.reps}{x.weightKg > 0 ? ` · ${x.weightKg} кг` : ' · без отягощения'}</p>)}{e.description && <p className="sport-note">{e.description}</p>}{(current.role === 'parent' || e.participantIds[0] === current.id) && <div className="family-row">{!e.archived && <button disabled={data.busy} onClick={() => setEditor({ entry: e, draft: entryDraft(e) })}>Редактировать</button>}<button disabled={data.busy} onClick={() => { void data.act(e, { action: e.archived ? 'restore' : 'archive' }) }}>{e.archived ? 'Восстановить' : 'В архив'}</button></div>}</article>)}</div>
      </>}
    </section><footer className="family-footer">Записи видны семье. Ребёнок ведёт свои занятия, родитель может помочь каждому.</footer>
  </section>
}

function SportEditor({ initial, current, participants, busy, stale, onReload, onClose, onSave }: { initial: FamilyDraft; current: Participant; participants: Participant[]; busy: boolean; stale: boolean; onReload: () => void; onClose: () => void; onSave: (draft: FamilyDraft) => Promise<void> }) {
  const [draft, setDraft] = useState(() => ({ ...initial, sport: { ...initial.sport!, exercises: initial.sport?.exercises ?? [] } }))
  const sport = draft.sport!
  function patchSport(patch: Partial<SportSession>) { setDraft(d => ({ ...d, sport: { ...d.sport!, ...patch } })) }
  return <section className="family-editor"><h2>Запись занятия</h2>{stale && <p role="alert">Запись изменена на другом устройстве. <button onClick={onReload}>Загрузить актуальную версию</button></p>}<form onSubmit={e => { e.preventDefault(); void onSave({ ...draft, title: draft.title.trim() || sport.activity.trim(), sport: { ...sport, activity: sport.activity.trim(), exercises: sport.exercises.map(x => ({ ...x, name: x.name.trim() })) } }) }}><fieldset disabled={busy || stale}>
    <div className="sport-filters"><label>Участник<select value={draft.participantIds[0]} onChange={e => setDraft({ ...draft, participantIds: [Number(e.target.value)] })}>{participants.filter(p => p.active && (current.role === 'parent' || p.id === current.id)).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Дата<input required type="date" min="2000-01-01" max={localDate()} value={draft.date} onInput={e => setDraft({ ...draft, date: e.currentTarget.value })} /></label><label>Вид спорта<input required maxLength={80} list="sport-activities" value={sport.activity} onChange={e => patchSport({ activity: e.target.value })} /><datalist id="sport-activities">{['Общая тренировка', 'Силовая тренировка', 'Бег', 'Ходьба', 'Плавание', 'Велосипед', 'Футбол', 'Гимнастика', 'Танцы'].map(a => <option key={a} value={a} />)}</datalist></label><label>Длительность, мин<input required type="number" min={0.1} max={1440} step="any" value={sport.minutes || ''} onChange={e => patchSport({ minutes: Number(e.target.value) })} /></label><label>Дистанция, км (необязательно)<input type="number" min={0} max={2000} step="any" value={sport.distanceKm || ''} onChange={e => patchSport({ distanceKm: Number(e.target.value) })} /></label></div>
    <label>Название (необязательно)<input maxLength={160} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label>
    <h3>Упражнения</h3><p>При необходимости добавьте подходы с одинаковым весом и числом повторений. Разные подходы можно записать отдельными строками.</p>
    {sport.exercises.map((x, i) => <div className="sport-exercise" key={i}>{(['name', 'sets', 'reps', 'weightKg'] as const).map(field => <label key={field}>{{ name: 'Упражнение', sets: 'Подходы', reps: 'Повторения', weightKg: 'Вес, кг' }[field]}<input required={field !== 'weightKg'} type={field === 'name' ? 'text' : 'number'} maxLength={field === 'name' ? 100 : undefined} min={field === 'weightKg' ? 0 : 1} max={field === 'sets' ? 100 : field === 'reps' ? 10000 : field === 'weightKg' ? 1000 : undefined} step={field === 'weightKg' ? 'any' : 1} value={x[field]} onChange={e => patchSport({ exercises: sport.exercises.map((item, n) => n === i ? { ...item, [field]: field === 'name' ? e.target.value : Number(e.target.value) } : item) })} /></label>)}<button type="button" aria-label={`Удалить упражнение ${i + 1}`} onClick={() => patchSport({ exercises: sport.exercises.filter((_, n) => n !== i) })}>Убрать</button></div>)}
    <button type="button" disabled={sport.exercises.length >= 50} onClick={() => patchSport({ exercises: [...sport.exercises, { name: '', sets: 3, reps: 10, weightKg: 0 }] })}>+ Упражнение</button>
    <label>Заметки и самочувствие<textarea maxLength={4000} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><button className="family-primary" type="submit">{busy ? 'Сохраняем…' : 'Сохранить занятие'}</button>
  </fieldset><button type="button" disabled={busy} onClick={onClose}>Отмена</button></form></section>
}
