import { useEffect, useState } from 'react'
import { useRuntime } from '../../application/runtime'
import type { ActivityReward } from '../../domain/learning'
import '../family/family.css'
export function ActivityRewards() {
 const { gateway } = useRuntime()
 const [items, setItems] = useState<ActivityReward[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true)
 const [attempt, setAttempt] = useState(0)
 useEffect(() => { let active = true; setLoading(true); setError(''); void gateway.activityRewards().then(v => { if (active) setItems(v) }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Не удалось загрузить награды') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [gateway, attempt])
 return <section className="family-life"><h1>Мои звёзды и улыбки</h1><p>Эти награды уже включены в рейтинги дня, недели и месяца вместе с наградами за дела.</p><div className="family-callout"><p>🏠 Дела: базовая ценность × средняя оценка / 5, после подтверждения. Например, дело на 30 ⭐ с оценкой 4 приносит 24 ⭐. Улыбки за дела отдельно не начисляются.</p><p>🙂 Поведение: каждая оценка 1–5 даёт столько же улыбок; повторная оценка того же человека за день заменяет предыдущую.</p><p>🔢 Математика: в новых занятиях 2–6 ⭐ за верный ответ с учётом сложности, действия и способа ответа. Максимум 40 ⭐ в день по Минску. Ранее начатые занятия сохраняют прежние правила; после этого обучение продолжается без новых звёзд.</p><p>📖 Чтение: 6 / 9 / 12 ⭐ за занятие из 6 карточек на уровнях 1 / 2 / 3. По отметке о завершении, до 30 ⭐ в день по Минску, отдельно от математики.</p><p>🏃 Спорт: 30 ⭐ + 2 🙂 за занятия, один раз на участника в день.</p><p>🌱 Привычка: 5 ⭐ + 1 🙂 за участие по расписанию, один раз в день за каждую привычку.</p><p>🧭 Приключение: 40 ⭐ + 3 🙂 каждому назначенному участнику после всех шагов; если участники не назначены — тем, кто выполнял шаги.</p><p>Одно действие учитывайте либо в делах, либо в привычках/спорте, чтобы не награждать его дважды. Заработанные ранее награды сохраняются.</p></div>{loading ? <p role="status">Загружаем награды…</p> : error ? <p role="alert">{error}<button onClick={() => setAttempt(v => v + 1)}>Повторить</button></p> : <><h2>Последние начисления</h2>{!items.length && <p>Первое достижение впереди. Запиши тренировку, отметь привычку или реши пример.</p>}<div className="family-grid">{items.map(r => <article className="family-card" key={`${r.source}/${r.sourceKey}/${r.participantId}`}><h3>{r.title}</h3><p>{r.date} · {{ reading: 'Чтение', math: 'Математика', habit: 'Привычка', adventure: 'Приключение', sport: 'Спорт' }[r.source]}</p><strong>+{r.stars} ⭐ {r.smiles > 0 && `+${r.smiles} 🙂`}</strong></article>)}</div>{items.length === 200 && <p>Показаны последние 200 начислений. Полная история сохранена.</p>}</>}</section>
}
