import { useEffect, useRef, useState } from 'react'
import { useRuntime } from '../../application/runtime'
import { mathLevels, mathSymbols, mathStars, type MathSettings, type MathView } from '../../domain/learning'
import { MathWork } from './MathWork'
import '../family/family.css'
import './learning.css'
export function MathTraining({ onReward }: { onReward: () => void }) {
 const { gateway } = useRuntime()
 const [settings, setSettings] = useState<MathSettings>({ operation: '+', level: 'easy', answerMode: 'input', divisionMode: 'full', allowNegative: false })
 const [history, setHistory] = useState<MathView[]>([]), [session, setSession] = useState<MathView | null>(null)
 const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [feedback, setFeedback] = useState(false), [attempt, setAttempt] = useState(0)
 const lock = useRef(false), mounted = useRef(false)
 useEffect(() => { mounted.current = true; let active = true; setLoading(true); setError(''); void gateway.mathSessions().then(v => { if (active) { setHistory(v); if (v[0]) setSettings(v[0].settings) } }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Не удалось загрузить занятия') }).finally(() => { if (active) setLoading(false) }); return () => { active = false; mounted.current = false } }, [gateway, attempt])
 async function mutate(fn: () => Promise<MathView>, answered: boolean) {
  if (lock.current) return
  lock.current = true; setBusy(true); setError('')
  try { const saved = await fn(); if (!mounted.current) return; setSession(saved); setFeedback(answered || (!!saved.feedback && !!saved.question)); setHistory(items => [saved, ...items.filter(x => x.id !== saved.id)]); if (answered) onReward() }
  catch (e) { if (mounted.current) setError(e instanceof Error ? e.message : 'Не удалось сохранить ответ. Попробуй ещё раз — награда не удвоится.') }
  finally { lock.current = false; if (mounted.current) setBusy(false) }
 }
 const active = history.find(s => !s.finished && s.index < s.total)
 const completed = history.filter(s => s.finished || s.index === s.total)
 const result = session?.feedback
 return <section className="family-life math-training"><header className="family-row"><div><p className="eyebrow">Учимся считать · твой личный прогресс</p><h1>Математика 🔢</h1><p>За верные ответы — до 30 ⭐ в день. Потом можно тренироваться дальше. Ошибки помогают учиться и не отнимают звёзды!</p></div>{session && <button disabled={busy} onClick={() => { setSession(null); setFeedback(false); setError('') }}>К моим занятиям</button>}</header>
 {error && <p role="alert" className="notice">{error}{!session && <button onClick={() => setAttempt(v => v + 1)}>Повторить загрузку</button>}</p>}
 {loading ? <p role="status">Загружаем занятия…</p> : !session ? <>
 {active ? <div className="family-callout"><h2>Продолжим занятие?</h2><p>{mathSymbols[active.settings.operation]} · {mathLevels[active.settings.level]} · решено {active.index} из {active.total}</p><button className="family-primary" onClick={() => { setSession(active); setFeedback(!!active.feedback) }}>Продолжить</button></div> : <form className="family-editor" onSubmit={e => { e.preventDefault(); void mutate(() => gateway.startMath(settings), false) }}><fieldset disabled={busy}><legend>Выбери занятие</legend><div className="math-operations">{(['+', '-', '*', ':'] as const).map(op => <button type="button" key={op} aria-pressed={settings.operation === op} aria-label={{ '+': 'Сложение', '-': 'Вычитание', '*': 'Умножение', ':': 'Деление' }[op]} onClick={() => setSettings({ ...settings, operation: op })}>{mathSymbols[op]}</button>)}</div><div className="family-fields"><label>Уровень<select value={settings.level} onChange={e => { const level = e.target.value as MathSettings['level']; setSettings({ ...settings, level, answerMode: level === 'columnar' ? 'input' : settings.answerMode }) }}>{Object.entries(mathLevels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label>{settings.level !== 'columnar' && <label>Как отвечать<select value={settings.answerMode} onChange={e => setSettings({ ...settings, answerMode: e.target.value as MathSettings['answerMode'] })}><option value="input">Ввод ответа</option><option value="choice">4 варианта</option></select></label>}{settings.operation === '-' && settings.level !== 'columnar' && <label className="family-checkbox"><input type="checkbox" checked={settings.allowNegative} onChange={e => setSettings({ ...settings, allowNegative: e.target.checked })} />Ответы с минусом</label>}{settings.operation === ':' && settings.level === 'columnar' && <label>Режим деления<select value={settings.divisionMode} onChange={e => setSettings({ ...settings, divisionMode: e.target.value as MathSettings['divisionMode'] })}><option value="result">Только итог</option><option value="steps">Шаги: произведения и остатки</option><option value="full">Полный: со сносом цифр</option></select></label>}</div><p>{settings.level === 'medium' ? 12 : settings.level === 'hard' ? 15 : 8} примеров · {mathStars(settings)} ⭐ за правильный ответ, в пределах 30 ⭐ за день во всех занятиях. День начинается в 00:00 по Минску. В делении ответ всегда целый.</p><button className="family-primary" type="submit">{busy ? 'Готовим примеры…' : 'Начать'}</button></fieldset></form>}
 <h2>Мои результаты</h2><div className="family-stats"><div><strong>{completed.length}</strong><span>завершённых занятий</span></div><div><strong>{history.reduce((sum, s) => sum + s.correct, 0)}</strong><span>верных ответов</span></div><div><strong>{history.reduce((sum, s) => sum + s.stars, 0)} ⭐</strong><span>за последние 100 занятий</span></div></div><div className="family-grid">{completed.map(s => <article className="family-card" key={s.id}><h3>{mathSymbols[s.settings.operation]} · {mathLevels[s.settings.level]}</h3><p>{new Date(s.createdAt).toLocaleDateString('ru-RU')} · {s.correct}/{s.total} верно</p><strong>{s.stars} ⭐ · серия {s.bestStreak}</strong></article>)}</div>
 </> : <>{!session.finished && <button disabled={busy} onClick={() => { void mutate(() => gateway.finishMath(session.id), false) }}>Закончить сейчас и сохранить результат</button>}<div className="math-progress"><progress aria-label={`Решено ${session.index} из ${session.total}`} max={session.total} value={session.index} /><strong>{session.index}/{session.total} · {session.stars} ⭐</strong></div>
 {feedback && result ? <section className="math-feedback" role="status"><h2>{result.correct ? 'Правильно! 🎉' : 'Разберёмся вместе 💛'}</h2><p>{result.question.left} {mathSymbols[session.settings.operation]} {result.question.right} = {result.expected.answer}</p>{result.correct ? <strong>{result.stars > 0 ? `+${result.stars} ⭐` : 'Сегодня все 30 ⭐ уже заработаны. Отличная работа! Продолжай для тренировки или отдохни.'}</strong> : <><p>За этот пример звёзды не начислены. Посмотри решение и попробуй следующий.</p>{result.fields.length > 1 && <details open><summary>Правильные шаги</summary>{result.fields.filter(f => f.key !== 'answer').map(f => <p key={f.key}>{f.label}: <strong>{result.expected[f.key]}</strong></p>)}</details>}</>}<button className="family-primary" onClick={() => setFeedback(false)}>{session.finished ? 'Посмотреть результат' : 'Следующий пример'}</button></section> : session.question ? <MathWork key={`${session.id}-${session.index}`} session={session} busy={busy} onSubmit={values => mutate(() => gateway.answerMath(session.id, session.index, values), true)} /> : <section className="family-empty"><h2>Занятие завершено! 🎉</h2><p>Правильных ответов: {session.correct} из {session.total}. Лучшая серия: {session.bestStreak}.</p><h2>Заработано {session.stars} ⭐</h2><p>Звёзды уже добавлены в твой рейтинг.</p><button onClick={() => setSession(null)}>Выбрать новое занятие</button></section>}
 </>}
 </section>
}
